import { createFileRoute, Link } from '@tanstack/react-router';
import { useEffect, useState } from 'react';
import { Building2, CalendarDays, MapPin, Search, SlidersHorizontal } from 'lucide-react';
import { SiteHeader, SiteFooter, pageHead } from '@/components/SiteChrome';
import { Button } from '@/components/ui/button';
import { supabase } from '@/integrations/supabase/client';
import { useAccount } from '@/components/Account';
import { PrivateState } from '@/components/PrivateState';

type SearchParams={q?:string}; type Practice={id:string;school_name:string;district:string;practice_type:string;start_date:string|null;end_date:string|null;status:string;progress:number};
export const Route=createFileRoute('/amaliyot')({validateSearch:(s:Record<string,unknown>):SearchParams=>typeof s['q']==='string'?{q:s['q']}: {},head:()=>pageHead('Amaliyotni izlash — CHDPU 4+2','Shaxsiy CHDPU amaliyot ma’lumotlarini xavfsiz qidiring va jarayon holatini ko‘ring.'),component:PracticePage});
function PracticePage(){const {q}=Route.useSearch();const {user,loading}=useAccount();const [query,setQuery]=useState(q??'');const [district,setDistrict]=useState('');const [school,setSchool]=useState('');const [rows,setRows]=useState<Practice[]>([]);const [error,setError]=useState(false);const [searched,setSearched]=useState(Boolean(q));
async function load(){if(!user)return;setError(false);let request=supabase.from('practices').select('id,school_name,district,practice_type,start_date,end_date,status,progress');if(query.trim()){const term=query.trim().replace(/[%(),.*]/g,'');const {data: profile}=await supabase.from('profiles').select('full_name').eq('id',user.id).maybeSingle();if(profile?.full_name?.toLocaleLowerCase().includes(term.toLocaleLowerCase())){/* Show this signed-in student's own practices only. */}else if(/^[0-9a-f]{8}-[0-9a-f-]{27,}$/i.test(term))request=request.eq('id',term);else request=request.or(`school_name.ilike.%${term}%,district.ilike.%${term}%`);}if(district)request=request.ilike('district',`%${district}%`);if(school)request=request.ilike('school_name',`%${school}%`);const {data,error:e}=await request;if(e)setError(true);else setRows(data??[]);setSearched(true)}
useEffect(()=>{if(user&&q)void load()},[user]);return <><SiteHeader/><main className="inner-page"><section className="page-intro container"><span className="section-index">AMALIYOT REYESTRI</span><h1>Amaliyotingizni<br/><em>toping.</em></h1><p>Shaxsiy amaliyot yozuvlari faqat tizimga kirgan talabaga ko‘rinadi.</p></section><section className="container search-workspace"><form onSubmit={e=>{e.preventDefault();void load()}}><div className="workspace-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="F.I.Sh. yoki amaliyot ID" aria-label="F.I.Sh. yoki amaliyot ID"/><Button type="submit">Qidirish</Button></div><div className="filters"><span><SlidersHorizontal/> FILTERLAR</span><label><MapPin/> Tuman<input value={district} onChange={e=>setDistrict(e.target.value)} placeholder="Masalan, Chirchiq"/></label><label><Building2/> Maktab<input value={school} onChange={e=>setSchool(e.target.value)} placeholder="Maktab nomi"/></label></div></form></section><section className="container result-area">{loading?<div className="skeleton-list"><i/><i/><i/></div>:!user?<PrivateState type="login"/>:error?<PrivateState type="error" onRetry={()=>void load()}/>:rows.length?<div className="result-list">{rows.map(r=><article key={r.id}><div><small>{r.practice_type}</small><h2>{r.school_name}</h2><p><MapPin/>{r.district}</p></div><div><small>JARAYON</small><strong>{r.progress}%</strong><div className="result-progress"><i style={{width:`${r.progress}%`}}/></div></div><div><small>HOLATI</small><span className="result-status">{r.status}</span></div></article>)}</div>:searched?<PrivateState type="empty"/>:<div className="result-prompt"><CalendarDays/><h2>Qidiruvga tayyor</h2><p>Filtrlarni kiriting yoki barcha shaxsiy yozuvlarni ko‘rish uchun “Qidirish”ni bosing.</p></div>}</section></main><SiteFooter/></>}
