CREATE TYPE public.app_role AS ENUM ('student', 'supervisor', 'faculty', 'practice_office', 'admin');
CREATE TABLE public.profiles (id uuid PRIMARY KEY, full_name text NOT NULL DEFAULT '', faculty text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own profile" ON public.profiles FOR SELECT TO authenticated USING (id = auth.uid());
CREATE POLICY "Create own profile" ON public.profiles FOR INSERT TO authenticated WITH CHECK (id = auth.uid());
CREATE POLICY "Update own profile" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE (user_id, role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own roles" ON public.user_roles FOR SELECT TO authenticated USING (user_id = auth.uid());
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = _user_id AND role = _role) $$;
CREATE TABLE public.practices (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), student_id uuid NOT NULL, school_name text NOT NULL, district text NOT NULL, practice_type text NOT NULL DEFAULT '4+2 pedagogik amaliyot', start_date date, end_date date, status text NOT NULL DEFAULT 'planned', progress integer NOT NULL DEFAULT 0 CHECK (progress BETWEEN 0 AND 100), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.practices TO authenticated; GRANT ALL ON public.practices TO service_role;
ALTER TABLE public.practices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own practices" ON public.practices FOR SELECT TO authenticated USING (student_id = auth.uid());
CREATE TABLE public.practice_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), practice_id uuid NOT NULL REFERENCES public.practices(id) ON DELETE CASCADE, title text NOT NULL, due_date date, status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.practice_tasks TO authenticated; GRANT ALL ON public.practice_tasks TO service_role;
ALTER TABLE public.practice_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own tasks" ON public.practice_tasks FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.practices p WHERE p.id = practice_id AND p.student_id = auth.uid()));
CREATE TABLE public.attendance (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), practice_id uuid NOT NULL REFERENCES public.practices(id) ON DELETE CASCADE, attended_on date NOT NULL, status text NOT NULL DEFAULT 'pending', created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT ON public.attendance TO authenticated; GRANT ALL ON public.attendance TO service_role;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Read own attendance" ON public.attendance FOR SELECT TO authenticated USING (EXISTS (SELECT 1 FROM public.practices p WHERE p.id = practice_id AND p.student_id = auth.uid()));
CREATE OR REPLACE FUNCTION public.set_updated_at() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$ BEGIN NEW.updated_at = now(); RETURN NEW; END $$;
CREATE TRIGGER profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER practices_updated_at BEFORE UPDATE ON public.practices FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER tasks_updated_at BEFORE UPDATE ON public.practice_tasks FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER attendance_updated_at BEFORE UPDATE ON public.attendance FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();